EntertainmentStreaming/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url


from accounts import urls as accountsUrls

#Media and static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
#    re_path(r'^/', include('accounts.urls')),
    re_path(r'^tv/', include('tv.urls')),
    re_path(r'^movies/', include('movies.urls')),
    url(r'^', include(accountsUrls, namespace="accounts")),
    re_path(r'^payments/', include('payments.urls')),
    re_path(r'^', include('main.urls')),
    re_path(r'^', include('series.urls')),        
]

#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'Movies'

urlpatterns = [
	url('movie/(?P<slug>[-\w]+)/$', views.MovieDetailView.as_view(), name="MovieDetail"),
	url('movies/$', views.MoviesListView.as_view(), name="MoviesList"),
]

tv/urls.py
from django.conf.urls import url
from . import views

app_name = 'TV'

urlpatterns = [
	url('channel/(?P<slug>[-\w]+)/$', views.ChannelDetailView.as_view(), name="ChannelDetail"),
	url('channels/$', views.ChannelsListView.as_view(), name="ChannelsList"),
]

movies/models.py
from django.db import models
import datetime

class Category(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name_plural = "categories"

class Movie(models.Model):

	link_status_choices = (
		('Functional','Functional'),
		('Broken or Misspelled','Broken or Misspelled'),
	)

	category = models.ForeignKey(Category, related_name="category", on_delete=models.CASCADE)
	name = models.CharField(max_length=50)
	link = models.TextField()
	image = models.TextField()
	synopsis = models.TextField()
	year = models.IntegerField()
	duration = models.DurationField()
	slug = models.SlugField(max_length=200, unique=True)
	link_status = models.CharField(max_length=20, default="Functional", choices=link_status_choices)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name']

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
import operator
from functools import reduce
import random

class MoviesListView(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = 'movies/list_movies.html'
		categories = Category.objects.all()

		query = request.GET.get("query")

		ListOfMoviesByCategory = []

		for category in categories:
			if query:
				ListOfMoviesByCategory.append({'category': category.name, 'movies': Movie.objects.filter(category=category, link_status="Functional", name__contains=query)})
			else:
				ListOfMoviesByCategory.append({'category': category.name, 'movies': Movie.objects.filter(category=category, link_status="Functional")})

		context = {
			'ListOfMoviesByCategory': ListOfMoviesByCategory,
		}
		return render(request, template_name, context)

class MovieDetailView(View):
	@method_decorator(login_required)
	def get(self, request, slug):
		template_name = 'movies/detail_movie.html'
		movie = get_object_or_404(Movie, slug=slug)
		name_movie = movie.name.split()
		category = Category.objects.get(pk=movie.category.pk)
		similarMovies = Movie.objects.filter(category=category).exclude(pk=movie.pk)

		condition1 = reduce(operator.or_,[Q(name__icontains=word) for word in name_movie])
		similarMovies = similarMovies.filter(Q(condition1) | Q(year=movie.year))

		listMovies = list(similarMovies)

		if len(listMovies) < 6:
			randomMovies = random.sample(listMovies, len(listMovies))
		else:
			randomMovies = random.sample(listMovies, 6)

		context = {
			'movie': movie,
			'category': category,
			'randomMovies': randomMovies,
		}
		return render(request, template_name, context)

movies/templates/movies/MovieDetail.html
{%extends 'base.html'%}

{%block content%}

	<div class="row">
		<div class="col-md-7">
			<h2>{{movie.name}}</h2>
			<video controls autoplay style="width: 100%;" controlsList="nodownload">
			<source src="{{movie.link}}" type="video/mp4">
			Your browser does not support the video tag.
			</video>
		</div>
		<div class="col-md-5">
			<h3>Synopsis</h3>
			<p class="text-justify">{{movie.synopsis}}</p>

			<p>Year: {{movie.year}}</p>
			<p>Duration: {{movie.duration}}</p>
		</div>
	</div>

	<div class="row">
	<div class="col-12">
	<h3 class="sub-title">Suggestions</h3>
	</div>

	{%for similarMovie in similarMovies%}
	<div class="col-4 col-sm-3 col-md-2">
	<a href="{%url 'Movies:MovieDetail' movie.slug%}">
	<img src="{{movie.image}}" alt="{{channel.name}}" class="d-block mx-auto" style="width: 100%;">
	</a>
	<p class="text-center">{{movie.name}}</p>
	</div>
	{%endfor%}
	</div>

{%endblock content%}

movies/templates/movies/MoviesList.html
{%extends 'base.html'%}

{%block content%}

	<div class="row">
		<div class="col-12">

		{%for MoviesByCategory in ListOfMoviesByCategory%}

			<h2>{{MoviesByCategory.category}}</h2>

			<div class="row">

			{%for movie in MoviesByCategory.movies%}

				<div class="col-4 col-sm-3 col-md-2">
					<a href="{%url 'Movies:MovieDetail' movie.slug%}">
						<img src="{{movie.image}}" alt="{{channel.name}}" class="d-block mx-auto" style="width: 100%;">
					</a>
					<p class="text-center">{{movie.name}}</p>
				</div>

			{%empty%}

				<div class="col-12">
					<p>Movie list empty</p>
				</div>

			{%endfor%}

			</div>

		{%endfor%}

		</div>
	</div>

{%endblock content%}

movies/templates/movies/detail_movie.html
{%extends 'base.html'%}

{%block content%}

	<style type="text/css">
	.embed-container {
	    position: relative;
	    padding-bottom: 56.25%;
	    height: 0;
	    overflow: hidden;
	}
	.embed-container iframe {
	    position: absolute;
	    top:-52px;
	    left: 0;
	    width: 100%;
	    height: 100%;
	}	
	</style>

	<div class="row">
		<div class="col-md-7">
			<h2>{{movie.name}}</h2>
			{%if '.mp4' in movie.link or '.mkv' in movie.link%}
			<video controls autoplay controlsList="nodownload"  style="width: 100%;">
			<source src="{{movie.link}}">
			Your browser does not support the video tag.
			</video>
			{%else%}
			<div class="embed-container">
			<iframe width="640" height="360" src="{{movie.link}}" frameborder="0" allowfullscreen></iframe>
			</div>
			{%endif%}
		</div>
		<div class="col-md-5">
			<h3>Synopsis</h3>
			<p class="text-justify">{{movie.synopsis}}</p>

			<p>Year: {{movie.year}}</p>
			<p>Duration: {{movie.duration}}</p>
		</div>
	</div>

	<div class="row">
	<div class="col-12">
	<h3 class="sub-title">Suggestions</h3>
	</div>

	{%for randomMovie in randomMovies%}
	<div class="col-4 col-sm-3 col-md-2">
	<a href="{%url 'Movies:MovieDetail' randomMovie.slug%}">
	<img src="{{randomMovie.image}}" alt="{{randomMovie.name}}" class="d-block mx-auto" style="width: 100%;">
	</a>
	<p class="text-center">{{randomMovie.name}}<br> {{randomMovie.year}}</p>
	</div>
	{%endfor%}
	</div>

{%endblock content%}

movies/templates/movies/list_movies.html
{%extends 'base.html'%}

{%block content%}

	<div class="row">
		<div class="col-12">

	<form method="GET" action="">
		<input type="text" name="query" placeholder="Nombre" value="{{request.GET.query}}">
		<input type="submit" value="Buscar">
	</form>

		{%for MoviesByCategory in ListOfMoviesByCategory%}

			<h2>{{MoviesByCategory.category}}</h2>

			<div class="row">

			{%for movie in MoviesByCategory.movies%}

				<div class="col-4 col-sm-3 col-md-2">
					<a href="{%url 'Movies:MovieDetail' movie.slug%}">
						<img src="{{movie.image}}" alt="{{channel.name}}" class="d-block mx-auto" style="width: 100%;">
					</a>
					<p class="text-center">{{movie.name}}<br>{{movie.year}}</p>
				</div>

			{%empty%}

				<div class="col-12">
					<p>Movie list empty</p>
				</div>

			{%endfor%}

			</div>

		{%endfor%}

		</div>
	</div>

{%endblock content%}