EntertainmentStreaming/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url


from accounts import urls as accountsUrls

#Media and static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
#    re_path(r'^/', include('accounts.urls')),
    re_path(r'^tv/', include('tv.urls')),
    re_path(r'^movies/', include('movies.urls')),
    url(r'^', include(accountsUrls, namespace="accounts")),
    re_path(r'^payments/', include('payments.urls')),
    re_path(r'^', include('main.urls')),
    re_path(r'^', include('series.urls')),        
]

#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

series/urls.py
from django.conf.urls import url
from . import views

app_name = 'Series'

urlpatterns = [
	url('chapter/(?P<slug>[-\w]+)/$', views.ChapterDetailView.as_view(), name="ChapterDetail"),
	url('serie/(?P<slug>[-\w]+)/$', views.SerieDetailView.as_view(), name="SerieDetail"),
	url('series/$', views.SeriesListView.as_view(), name="SeriesList"),
]

tv/urls.py
from django.conf.urls import url
from . import views

app_name = 'TV'

urlpatterns = [
	url('channel/(?P<slug>[-\w]+)/$', views.ChannelDetailView.as_view(), name="ChannelDetail"),
	url('channels/$', views.ChannelsListView.as_view(), name="ChannelsList"),
]

series/models.py
from django.db import models
from datetime import datetime
from django.template.defaultfilters import slugify

now = datetime.now()

class Category(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name_plural = "categories"

	def __str__(self):
		return self.name

class Serie(models.Model):
	category = models.ForeignKey(Category, related_name="category", on_delete=models.CASCADE)
	name = models.CharField(max_length=50)
	image = models.TextField()
	synopsis = models.TextField()
	year = models.IntegerField(default=now.year)
	slug = models.SlugField(max_length=200, unique=True)

	def __str__(self):
		return self.name

class Season(models.Model):
	serie = models.ForeignKey(Serie, related_name="serie", on_delete=models.CASCADE)
	number = models.IntegerField()
	year = models.IntegerField()

	def __str__(self):
		return str(self.number) + " of " + self.serie.name

class Chapter(models.Model):
	link_status_choices = (
		('Functional','Functional'),
		('Broken or Misspelled','Broken or Misspelled'),
	)
	season = models.ForeignKey(Season, related_name="season", on_delete=models.CASCADE)
	number = models.IntegerField()
	name = models.CharField(max_length=50)
	link = models.TextField()
	synopsis = models.TextField()
	duration = models.DurationField()
	slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
	link_status = models.CharField(max_length=20, default="Functional", choices=link_status_choices)

	def __str__(self):
		return str(self.number) + "x" +str(self.season)

	def save(self, *args, **kwargs):
		print(self.season.number)
		self.slug= '-'.join((slugify(self.season.number), slugify(self.number), slugify(self.season.serie.name)))
		super(Chapter, self).save(*args, **kwargs)

series/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
import operator
from functools import reduce
import random

class SeriesListView(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = 'series/list_series.html'
		categories = Category.objects.filter()

		request.user.profile.update_status()
		
		ListOfSeriesByCategory = []

		for category in categories:
			ListOfSeriesByCategory.append({'category': category.name, 'series': Serie.objects.filter(category=category)})

		context = {
			'ListOfSeriesByCategory': ListOfSeriesByCategory,
		}
		return render(request, template_name, context)

class SerieDetailView(View):
	@method_decorator(login_required)
	def get(self, request, slug):
		template_name = 'series/detail_serie.html'
		serie = Serie.objects.get(slug=slug)
		seasons = Season.objects.filter(serie=serie)
		request.user.profile.update_status()
		
		ListOfChaptersBySeason = []

		for season in seasons:
			ListOfChaptersBySeason.append({'season': season.number, 'chapters': Chapter.objects.filter(season=season)})

		context = {
			'serie': serie,
			'ListOfChaptersBySeason': ListOfChaptersBySeason,
		}
		return render(request, template_name, context)

class ChapterDetailView(View):
	@method_decorator(login_required)
	def get(self, request, slug):
		template_name = 'series/detail_chapter.html'
		chapter = Chapter.objects.get(slug=slug)

		context = {
			'chapter': chapter,
		}
		return render(request, template_name, context)		

series/templates/series/detail_chapter.html
{%extends 'base.html'%}

{%block content%}

	<style type="text/css">
	.embed-container {
	    position: relative;
	    padding-bottom: 56.25%;
	    height: 0;
	    overflow: hidden;
	}
	.embed-container iframe {
	    position: absolute;
	    top:-52px;
	    left: 0;
	    width: 100%;
	    height: 100%;
	}	
	</style>

	<div class="row">
		<div class="col-md-7">
			<h2>{{chapter.name}}</h2>
			{%if '.mp4' in movie.link or '.mkv' in movie.link%}
			<video controls autoplay controlsList="nodownload"  style="width: 100%;">
			<source src="{{chapter.link}}">
			Your browser does not support the video tag.
			</video>
			{%else%}
			<div class="embed-container">
			<iframe width="640" height="360" src="{{chapter.link}}" frameborder="0" allowfullscreen></iframe>
			</div>
			{%endif%}
		</div>
		<div class="col-md-5">
			<h3>Synopsis</h3>
			<p class="text-justify">{{chapter.synopsis}}</p>
			<p>Duration: {{chapter.duration}}</p>
		</div>
	</div>

{%endblock content%}

series/templates/series/detail_serie.html
{%extends 'base.html'%}

{%block content%}

	<div class="row">
		<div class="col-12">

			<h2>{{serie}}</h2>
	{%for ChaptersBySeason in ListOfChaptersBySeason%}

			<h3>Season {{ChaptersBySeason.season}}</h3>
			<div class="row">

				<table class="table">
  					<thead>
    					<tr>
      						<th scope="col">Chapter</th>
							<th scope="col">Name</th>
							<th scope="col">Synopsis</th>
							<th scope="col">See</th>
						</tr>
					</thead>
					<tbody>

		{%for chapter in ChaptersBySeason.chapters%}

					<tr>
						<th scope="row">{{chapter.number}}</th>
						<td>{{chapter.name}}</td>
						<td>{{chapter.synopsis}}}</td>
						<td><a href="{%url 'Series:ChapterDetail' chapter.slug%}">Here</a></td>
					</tr>
		{%empty%}

					<tr>
						<td>Chapter list empty</td>
					</tr>

		{%endfor%}

					</tbody>
				</table>
			</div>

	{%endfor%}

		</div>
	</div>

{%endblock content%}

series/templates/series/list_series.html
{%extends 'base.html'%}

{%block content%}

	<div class="row">
		<div class="col-12">

	{%for SeriesByCategory in ListOfSeriesByCategory%}

			<h2>{{SeriesByCategory.category}}</h2>
			<div class="row">

		{%for serie in SeriesByCategory.series%}

				<div class="col-4 col-sm-3 col-md-2">
					<a href="{%url 'Series:SerieDetail' serie.slug%}">
						<img src="{{serie.image}}" alt="{{serie.name}}" class="d-block mx-auto" style="width: 100%;">
					</a>
					<p class="text-center" style="bottom: 0; ">{{serie.name}}</p>
				</div>

		{%empty%}

				<div class="col-12">	
					<p>Series list empty</p>
				</div>

		{%endfor%}

			</div>

	{%endfor%}

		</div>
	</div>

{%endblock content%}