EntertainmentStreaming/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url


from accounts import urls as accountsUrls

#Media and static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
#    re_path(r'^/', include('accounts.urls')),
    re_path(r'^tv/', include('tv.urls')),
    re_path(r'^movies/', include('movies.urls')),
    url(r'^', include(accountsUrls, namespace="accounts")),
    re_path(r'^payments/', include('payments.urls')),
    re_path(r'^', include('main.urls')),
    re_path(r'^', include('series.urls')),        
]

#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

app_name = 'accounts'

urlpatterns = [
	#Redirects
	url(r'^login', login,name="login"),
	url(r'^logout/$', logout, name="logout"),
	#Home
	url(r'^account/profile/$', views.ViewProfile.as_view(), name="Profile"),
	url(r'^account/home/$', views.ViewHome.as_view(), name="Home"),	
	#Accounts
	url(r'^accounts/new/$', views.CreateViewAccount.as_view(), name="CreateAccount"),
	url(r'^accounts/list/$', views.ListViewAccounts.as_view(), name="ListAccounts"),
	#Change password
	url(r'^password/$', views.change_password, name='change_password'),
	#Reset password
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
    ]

payments/urls.py
from django.conf.urls import url
from . import views

app_name = 'payments'

urlpatterns = [
	url('history/(?P<username>[-\w]+)/$', views.PaymentsListView.as_view(), name="PaymentsListClient"),
	url('history/$', views.PaymentsListView.as_view(), name="PaymentsList"),
]

tv/urls.py
from django.conf.urls import url
from . import views

app_name = 'TV'

urlpatterns = [
	url('channel/(?P<slug>[-\w]+)/$', views.ChannelDetailView.as_view(), name="ChannelDetail"),
	url('channels/$', views.ChannelsListView.as_view(), name="ChannelsList"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from payments.models import *
from dateutil.relativedelta import relativedelta

class Profile(models.Model):
	country_choices = (
		("MX", "Mexico"),
		("USA", "United States of America"),
	)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	photo = models.ImageField(upload_to="users/%Y/%m/%d", blank=True, default="/userDefault.png")
	phone = models.CharField(max_length=13, blank=True, null=True)
	country = models.CharField(max_length=10, choices=country_choices)
	is_enabled = models.BooleanField(default=True)
	monthly_payment = models.DecimalField(decimal_places=2, max_digits=5, null=True, blank=True)
	foreign_currency = models.CharField(max_length=10, null=True, blank=True)
	free_trial_deadline = models.DateTimeField(null=True, blank=True)
	is_premium = models.BooleanField(default=False)

	def __str__(self):
		return 'Profile of {} {}'.format(self.user.first_name, self.user.last_name)

	def update_status(self):
		if self.user.is_staff == False:
			now = timezone.now()
			last_payment = Payment.objects.filter(user=self.user).last()

			if last_payment is None:
				self.is_premium = False
				if now > self.user.profile.free_trial_deadline:
					self.is_enabled = False
				else:
					self.is_enabled = True
			else:
				self.is_premium = True
				if now > last_payment.deadline:
					self.is_enabled = False
				else:
					self.is_enabled = True
			self.save()

	def save(self, *args, **kwargs):
		#Define foreign currency and monthly payment
		if self.user.is_staff == False:
			if self.country == "USA":
				self.foreign_currency = "USD"
				self.monthly_payment = 10
			elif self.country == "MX":
				self.foreign_currency = "MXN"
				self.monthly_payment = 100

			#Define free_trial_deadline
			self.free_trial_deadline = self.user.date_joined + relativedelta(months=1)
		super(Profile, self).save(*args, **kwargs)

#You show complete name	
def get_full_name(self):
	return '{} {}'.format(self.first_name, self.last_name)

User.add_to_class("__str__", get_full_name)

class Visitor(models.Model):
	pupil = models.OneToOneField(User, null=False, on_delete=models.CASCADE)
	session_key = models.CharField(null=False, max_length=40)

	def __str__(self):
		return 'Key of {}'.format(self.pupil)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.forms.utils import ErrorList
from django.utils.translation import ugettext_lazy as _

class UserCreateForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(UserCreateForm, self).__init__(*args, **kwargs)
		self.fields['first_name'].required = True
		self.fields['last_name'].required = True
		self.fields['email'].required = True

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email', )

	def clean_email(self):
		cleaned_data = super(UserCreateForm, self).clean()
		email = cleaned_data.get("email")
		try:
			user = User.objects.exclude(pk=self.instance.pk).get(email=email)
#			print("souy e2", original_email)
		except User.DoesNotExist:
			return email
		raise forms.ValidationError(u'The email "%s" already registered.' % email)

#	def clean_email2(self):
#		email11 = self.cleaned_data['email']
#		e2 = self.cleaned_data.get('email2')
#		if email11 != e2:
#			raise forms.ValidationError('The email addresses do not match.')

class ProfileCreateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('country', 'phone')

class UserUpdateForm(forms.ModelForm):	
	class Meta:
		model = User
		fields = ('first_name', 'last_name')

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('photo', 'phone')

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import *
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from .forms import *
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

class ViewProfile(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/profile.html"
		profile = Profile.objects.get(user=request.user)
		UserForm = UserUpdateForm(instance=request.user)
		ProfileForm = ProfileUpdateForm(instance=profile)
		context = {
			'profile': profile,
			'UserForm': UserForm,
			'ProfileForm': ProfileForm,
		}
		return render(request,template_name, context)
	def post(self, request):
		template_name = "accounts/Profile.html"
		profile = Profile.objects.get(user=request.user)
		UserForm = UserUpdateForm(instance=request.user, data=request.POST)
		ProfileForm = ProfileUpdateForm(instance=profile, data=request.POST, files=request.FILES)

		if UserForm.is_valid: # or ProfileForm.is_valid:
			UserForm.save()
		if ProfileForm.is_valid:
			ProfileForm.save()
			messages.success(request, 'Your profile was successfully updated!')
		return redirect('accounts:Profile')

def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request, user)  # Important!
			messages.success(request, 'Your password was successfully updated!')
			return redirect('accounts:change_password')
		else:
		    messages.error(request, 'Please correct the error below.')
	else:
		form = PasswordChangeForm(request.user)
	return render(request, 'accounts/change_password.html', {'form': form})

class ViewHome(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = 'accounts/home.html'
		profile = Profile.objects.get(user=request.user)
		if request.user.is_staff == False:
			profile.update_status()
		return render(request, template_name)

class CreateViewAccount(View):
	def get(self, request):
		template_name = "accounts/create_account.html"
		UserForm = UserCreateForm()
		ProfileForm = ProfileCreateForm()
		last_account = User.objects.last()
		accounts_total = User.objects.filter(is_staff=False).count()
		context = {
			'UserForm':UserForm,
			'ProfileForm': ProfileForm
		}
		return render(request,template_name,context)
	def post(self,request):
		template_name = "accounts/create_account.html"
		last_account = User.objects.last()

		UserForm = UserCreateForm(request.POST)
		ProfileForm = ProfileCreateForm(request.POST, request.FILES)
		if UserForm.is_valid() and ProfileForm.is_valid():
			NewUser = UserForm.save(commit=False)
			NewUser.username = str(last_account.pk + 1)
			NewUser.set_password('timesee1')
			NewUser.save()

			NewProfile = ProfileForm.save(commit=False)
			NewProfile.user = NewUser
			NewProfile.save()
		else:
			context = {
				'UserForm':UserForm,
				'ProfileForm': ProfileForm
			}
			return render(request,template_name,context)
		return redirect('payments:PaymentsListClient', NewUser.username)

class ListViewAccounts(View):
	def get(self, request):
		template_name = "accounts/list_accounts.html"
		users = User.objects.filter(is_staff=False).order_by('pk')

		context = {
			'users': users
		}
		return render(request,template_name,context)

accounts/templates/accounts/Profile.html
{%extends 'base.html'%}

{%block content%}

<div class="row">
	<div class="col-12">
		<form action="." method="post" enctype="multipart/form-data">
			<br>
			{%csrf_token%}

					{%for field in UserForm%}

					{{field.label_tag}}
					<p><input id="{{field.id_for_label }}" type="text" name="{{field.html_name }}" placeholder="{{ field.label}}" class="form-control" value="{{field.value}}"/></p>

					{%endfor%}


					{{ProfileForm.photo.label_tag}}
					<p><input id="{{ProfileForm.photo.id_for_label}}" type="file" name="{{ProfileForm.photo.html_name}}" placeholder="{{ProfileForm.photo.label}}" class="form-control-file"/></p>

					{{ProfileForm.phone.label_tag}}
					<p><input id="{{ProfileForm.phone.id_for_label}}" type="text" name="{{ProfileForm.phone.html_name}}" placeholder="{{ProfileForm.phone.label}}" class="form-control" value="{{ProfileForm.phone.value}}" /></p>
			<button type="submit">Save changes</button>
		</form>
	</div>
</div>

{%endblock content%}

accounts/templates/accounts/change_password.html
{%extends 'base.html'%}

{%block content%}

	<div class="row">
		<div class="col-12">

		{% if messages %}

			<div class="messages">

			{% for message in messages %}
	
				<div class="alert alert-{{ message.tags }}">{{ message }}</div>

			{% endfor %}

			</div>

		{% endif %}

			<h3>Change your password</h3>
			</div>
			<div class="col-md-6">
			<form method="post">
				<div class="form-group">
					{% csrf_token %}

					{%for field in form%}

					<p><input id="{{ field.id_for_label}}" type="password" name="{{ field.html_name }}" placeholder="{{ field.label}}" class="form-control"/></p>

					{%endfor%}
					<button type="submit">Save changes</button>
				</div>
			</form>

		</div>
		<div class="col-md-6">
			Your password can't be too similar to your other personal information.<br>Your password must contain at least 8 characters.<br>Your password can't be a commonly used password.<br>Your password can't be entirely numeric.<br>
		</div>
	</div>



{%endblock content%}

accounts/templates/accounts/create_account.html
{%extends 'base.html'%}

{%block content%}
	<h1>Create account</h1>

	<form action="." method="post" class="centrar">
		{%csrf_token%}

		{%for field in UserForm%}

		<p><input id="{{ field.id_for_label }}" type="text" name="{{ field.html_name }}" placeholder="{{ field.label}}" class="form-control"/></p>
		{{ field.errors }}
		{%endfor%}

	{{ProfileForm.as_p}}
		<input type="submit" value="Create account">
	</form>

{%endblock content%}

accounts/templates/accounts/home.html
{%extends 'base.html'%}

{%block content%}

	<h1>Welcome {{request.user.get_full_name}}</h1>

{%endblock content%}

accounts/templates/accounts/list_accounts.html
{%extends 'base.html'%}

{%block content%}
	<div class="row">
		<div class="col-12">
		<h1>Accounts</h1>
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Username</th>
							<th>Name</th>
							<th>Email</th>
							<th>Country</th>
							<th>Enabled</th>
							<th>Actions</th>
						</tr>
					</thead>
	{%for user in users%}
					<tbody>
						<tr>
							<td>{{user.username}}</td>
							<td>{{user.get_full_name}}</td>
							<td>{{user.email}}</td>
							<td>{{user.profile.country}}</td>		
							<td>{{user.profile.is_enabled}}</td>
							<td><a href="{%url 'payments:PaymentsListClient' user.username%}">Pay</a></td>	
						</tr>

	{%empty%}

						<tr>
							<td colspan="8">Users list empty</td>
						</tr>
								
	{%endfor%}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{%endblock content%}

accounts/templates/accounts/profile.html
{%extends 'base.html'%}

{%block content%}

	<div class="row">
		<div class="col-12">
			<form action="." method="post" enctype="multipart/form-data">
				<br>
				{%csrf_token%}

						{%for field in UserForm%}

						{{field.label_tag}}
						<p><input id="{{field.id_for_label }}" type="text" name="{{field.html_name }}" placeholder="{{ field.label}}" class="form-control" value="{{field.value}}"/></p>

						{%endfor%}


						{{ProfileForm.photo.label_tag}}
						<p><input id="{{ProfileForm.photo.id_for_label}}" type="file" name="{{ProfileForm.photo.html_name}}" placeholder="{{ProfileForm.photo.label}}" class="form-control-file"/></p>

						{{ProfileForm.phone.label_tag}}
						<p><input id="{{ProfileForm.phone.id_for_label}}" type="text" name="{{ProfileForm.phone.html_name}}" placeholder="{{ProfileForm.phone.label}}" class="form-control" value="{{ProfileForm.phone.value}}" /></p>
						<p>Date joined: {{user.date_joined}}</p>
				<button type="submit">Save changes</button>
			</form>
		</div>
	</div>

{%endblock content%}

accounts/templates/accounts/reset_password.html
{%extends 'base.html'%}

{%block content%}

    <div class="row">
        <div class="col-12">
			<h2>Did you forget your password?</h2>

			<form method="post">
				<p>To reset your password, enter your email address. You may have to check your junk mail folder</p>
			    {% csrf_token %}
			    {{ form.as_p }}
			    <button type="submit">Enviar</button>
			</form>
		</div>
	</div>

{%endblock content%}

accounts/templates/accounts/reset_password_complete.html
{%extends 'base.html'%}

{%block content%}

    <div class="row">
        <div class="col-12">
			<h2>You have successfully changed your password</h2>

			<p><a href="{%url 'accounts:login'%}">Sign in</a></p>
		</div>
	</div>

{%endblock content%}

accounts/templates/accounts/reset_password_confirm.html
{%extends 'base.html'%}

{%block content%}

    <div class="row">
        <div class="col-12">

		{% if messages %}

			<div class="messages">

			{% for message in messages %}
	
				<div class="alert alert-{{ message.tags }}">{{ message }}</div>

			{% endfor %}

			</div>

		{% endif %}
		
			<h2>Did you forget your password?</h2>
			<p>Enter a new password for your account</p>
			<form method="post">
				{% csrf_token %}

					{%for field in form%}

					<p><input id="{{ field.id_for_label }}" type="password" name="{{ field.html_name }}" placeholder="{{ field.label}}" class="form-control"/></p>

					{%endfor%}

				<button type="submit">Reset password</button>
			</form>
		</div>
	</div>
	
{%endblock content%}

accounts/templates/accounts/reset_password_done.html
{%extends 'base.html'%}

{%block content%}

    <div class="row">
        <div class="col-12">
			<h2>Check your email</h2>
			<p>We have sent you by email with instructions to reset your password.</p>
			<p>If you do not receive an email, make sure you have entered the address with which you registered and check your spam folder.</p>
		</div>
	</div>
	
{%endblock content%}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You have received this email because you requested to reset the password for your account on TimeSee.{% endblocktrans %}

{% trans "If you request a password change, click on the link below. If you did not request this, ignore this email" %}
{% block reset_link %}

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, if you have forgotten it is:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}TimeSee Team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/viewProfile.html
{%extends 'base.html'%}

{%block content%}

<div class="row">
	<div class="col-12">
		<form action="." method="post" enctype="multipart/form-data">
			<br>
			{%csrf_token%}

					{%for field in UserForm%}

					{{field.label_tag}}
					<p><input id="{{field.id_for_label }}" type="text" name="{{field.html_name }}" placeholder="{{ field.label}}" class="form-control" value="{{field.value}}"/></p>

					{%endfor%}


					{{ProfileForm.photo.label_tag}}
					<p><input id="{{ProfileForm.photo.id_for_label}}" type="file" name="{{ProfileForm.photo.html_name }}" placeholder="{{ProfileForm.photo.label}}" class="form-control-file"/></p>

					{{ProfileForm.phone.label_tag}}
					<p><input id="{{ProfileForm.phone.id_for_label}}" type="text" name="{{ProfileForm.phone.html_name}}" placeholder="{{ProfileForm.phone.label}}" class="form-control" value="{{ProfileForm.phone.value}}" /></p>

			<button type="submit">Save changes</button>
		</form>
	</div>
</div>

{%endblock content%}