EntertainmentStreaming/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url


from accounts import urls as accountsUrls

#Media and static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
#    re_path(r'^/', include('accounts.urls')),
    re_path(r'^tv/', include('tv.urls')),
    re_path(r'^movies/', include('movies.urls')),
    url(r'^', include(accountsUrls, namespace="accounts")),
    re_path(r'^payments/', include('payments.urls')),
    re_path(r'^', include('main.urls')),
    re_path(r'^', include('series.urls')),        
]

#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

app_name = 'accounts'

urlpatterns = [
	#Redirects
	url(r'^login', login,name="login"),
	url(r'^logout/$', logout, name="logout"),
	#Home
	url(r'^account/profile/$', views.ViewProfile.as_view(), name="Profile"),
	url(r'^account/home/$', views.ViewHome.as_view(), name="Home"),	
	#Accounts
	url(r'^accounts/new/$', views.CreateViewAccount.as_view(), name="CreateAccount"),
	url(r'^accounts/list/$', views.ListViewAccounts.as_view(), name="ListAccounts"),
	#Change password
	url(r'^password/$', views.change_password, name='change_password'),
	#Reset password
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
    ]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
	url(r'^$', views.ViewMain.as_view(), name="Main"),
    ]

movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'Movies'

urlpatterns = [
	url('movie/(?P<slug>[-\w]+)/$', views.MovieDetailView.as_view(), name="MovieDetail"),
	url('movies/$', views.MoviesListView.as_view(), name="MoviesList"),
]

series/urls.py
from django.conf.urls import url
from . import views

app_name = 'Series'

urlpatterns = [
	url('chapter/(?P<slug>[-\w]+)/$', views.ChapterDetailView.as_view(), name="ChapterDetail"),
	url('serie/(?P<slug>[-\w]+)/$', views.SerieDetailView.as_view(), name="SerieDetail"),
	url('series/$', views.SeriesListView.as_view(), name="SeriesList"),
]

tv/urls.py
from django.conf.urls import url
from . import views

app_name = 'TV'

urlpatterns = [
	url('channel/(?P<slug>[-\w]+)/$', views.ChannelDetailView.as_view(), name="ChannelDetail"),
	url('channels/$', views.ChannelsListView.as_view(), name="ChannelsList"),
]

templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>TimeSee</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta charset="utf-8"/>
		<link rel="stylesheet" type="text/css" href="{%static '/css/styles.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	</head>
	<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{%if request.user.is_authenticated == False%}{%url 'main:Main'%}{%endif%}">TimeSee</a>

      {%if request.user.is_authenticated%}
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:Home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {%if request.user.profile.is_enabled == False%}disabled{%endif%}">
            <a class="nav-link" href="{%url 'TV:ChannelsList'%}">TV</a>
          </li>
          <li class="nav-item {%if request.user.profile.is_enabled == False%}disabled{%endif%}">
            <a class="nav-link" href="{%url 'Movies:MoviesList'%}">Movies</a>
          </li>
          <li class="nav-item {%if request.user.profile.is_enabled == False%}disabled{%endif%}">
            <a class="nav-link" href="{%url 'Series:SeriesList'%}">Series</a>
          </li>

          {%if request.user.is_staff%}
      
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Accounts
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{%url 'accounts:CreateAccount'%}">Create</a>
              <a class="dropdown-item" href="{%url 'accounts:ListAccounts'%}">List</a>
            </div>
          </li>      
      
          {%endif%}
      
        </ul>

        <ul class="navbar-nav ml-auto">

        {%if request.user.is_staff is False%}
          
          <span class="navbar-text">
          
            {%if request.user.profile.is_premium == True and request.user.profile.is_enabled == True%}Premium (Enabled) {%elif request.user.profile.is_premium == True and request.user.profile.is_enabled == False%}Premium (Locked){%elif request.user.profile.is_premium == False and request.user.profile.is_enabled == True%}Free trial (Enable){%else%} Free trial (Finished) {%endif%}

          </span>
          
          <li class="nav-item">
            <a class="nav-link" href="{%url 'payments:PaymentsList'%}">Payments</a>
          </li>
      
        {%endif%}
      
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{request.user.get_full_name}}
              <img src="{{request.user.profile.photo.url}}" class="myphoto">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{%url 'accounts:Profile'%}">profile</a>
              <a class="dropdown-item" href="{%url 'accounts:change_password'%}">change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{%url 'accounts:logout'%}">logout</a> 
            </div>
          </li>
        </ul>
      </div>
      
      {%endif%}
    </nav>  
 
		<section class="container content">
			
      {%block content%}
			{%endblock content%}
	
  	</section>
	</body>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-114419678-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-114419678-1');
  </script>
</html>